on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: Updates Blog Outline
    steps:
      - uses: actions/checkout@v3
      - name: Updates Blog Outline
        uses: WeiYun0912/github-action-demo@main